image: hseeberger/scala-sbt

cache:
  paths:
    - $PWD/.ivy2/
    - $PWD/.sbt/

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  GET_SOURCES_ATTEMPTS: 3
  GITHUB_PROJECT: iText4s

stages:
  - pre
  - test
  - publish

before_script:
  - printenv | grep '^[A-Z][A-Z_]*=.*' | grep -v '^_..*' | sort

mirror:
  stage: pre
  cache: {}
  script:
    - git push --mirror https://Morgaroth:${_GITHUB_ACCESS_TOKEN}@github.com/Morgaroth/${GITHUB_PROJECT}.git

tests:
  stage: test
  script:
    - sbt -ivy $PWD/.ivy2 -sbt-dir $PWD/.sbt test

release:
  stage: publish
  only:
    - master
  script:
    - mkdir ~/.ssh
    - ssh-keyscan -H -p 22 gitlab.com > ~/.ssh/known_hosts
    - echo "${_SSH_DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/*
    - git config user.name "Gitlab CI"
    - git config user.email $GITLAB_USER_EMAIL
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git config --list
    - sbt -ivy $PWD/.ivy2 -sbt-dir $PWD/.sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=${_BINTRAY_PASS} "release with-defaults"

  after_script:
    - rm -Rfv .ssh